from __future__ import annotations

from pathlib import Path

from .graph import GraphStore
from .stats import compute_stats


class MemoryError(ValueError):
    pass


def _memory_dir(root: Path) -> Path:
    return root.resolve() / ".contextopt" / "memory"


def _safe_name(name: str) -> str:
    normalized = name.strip().removesuffix(".md")
    if not normalized or any(part in normalized for part in ("/", "\\", "..")):
        raise MemoryError(f"invalid memory name: {name}")
    return f"{normalized}.md"


def memory_path(root: Path, name: str) -> Path:
    path = (_memory_dir(root) / _safe_name(name)).resolve()
    memory_root = _memory_dir(root).resolve()
    try:
        path.relative_to(memory_root)
    except ValueError as exc:
        raise MemoryError(f"memory path escapes root: {name}") from exc
    return path


def list_memories(root: Path) -> list[str]:
    directory = _memory_dir(root)
    if not directory.exists():
        return []
    return sorted(path.name for path in directory.glob("*.md") if path.is_file())


def read_memory(root: Path, name: str) -> str:
    path = memory_path(root, name)
    if not path.exists():
        raise MemoryError(f"memory not found: {name}")
    return path.read_text(encoding="utf-8", errors="replace")


def write_memory(root: Path, name: str, text: str) -> Path:
    path = memory_path(root, name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")
    return path


def build_project_memory(root: Path, store: GraphStore, *, notes: str = "") -> str:
    stats = compute_stats(root, store)
    lines = [
        "# CodePrism Project Memory",
        "",
        "Generated by `codeprism onboard`.",
        "",
        "## Project Snapshot",
        "",
        f"- Root: `{stats['root']}`",
        f"- Mapped files: {stats['mapped_files']}",
        f"- Graph nodes: {stats['graph_nodes']}",
        f"- Graph edges: {stats['graph_edges']}",
        f"- Source estimated tokens: {stats['source_estimated_tokens']}",
        f"- Context pack estimated tokens: {stats['context_pack_estimated_tokens']}",
        f"- Map status: {stats['freshness']['status']}",
        "",
        "## Agent Workflow",
        "",
        "1. Run `codeprism prime \"task\" --changed` when edits exist.",
        "2. Read the generated slice before broad raw files.",
        "3. Use `codeprism read PATH --mode signatures` before full files.",
        "4. Use `codeprism get NODE_ID` for exact mapped source.",
        "5. Use `codeprism gain` to check estimated savings and map freshness.",
    ]
    if notes.strip():
        lines += ["", "## Notes", "", notes.strip()]
    return "\n".join(lines) + "\n"


def write_project_memory(
    root: Path,
    store: GraphStore,
    *,
    notes: str = "",
    out: Path | None = None,
) -> Path:
    text = build_project_memory(root, store, notes=notes)
    path = out or memory_path(root, "project")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
